### ISSUE TITLE
Project is really, really gay.

### ISSUE THREAD

**Issue by dialupnoises** [robertdhernandez/budding-friendships#1]
Too much gayness. Was overwhelming.
pictured: jag trying to make game less gay

![99171__UNOPT__safe_pinkie-pie_glasses_book_reading_computer_artist-shout](https://f.cloud.github.com/assets/674054/113435/d2c4c8a0-6b55-11e2-8101-80357d129cfa.png)

**Comment by robertdhernandez** [comment]
![c for idiots](https://f.cloud.github.com/assets/1021995/116386/9653e6d4-6bf6-11e2-88bd-3b2c71d8822c.jpg)
